#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

start_service() {
	mkdir -p /tmp/opensocks /etc/opensocks
	chmod 0700 /etc/opensocks
	procd_open_instance
	procd_set_param command /usr/lib/opensocks/launcher.sh
	procd_set_param env GOMEMLIMIT=24MiB GOGC=50
	procd_set_param respawn 3600 5 5
	procd_set_param file /etc/config/opensocks
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
