include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-opensocks
PKG_VERSION:=0.1.0
PKG_RELEASE:=1
PKG_LICENSE:=GPL-3.0-or-later

LUCI_DEPENDS:=+opensocks +luci-base +luci-compat +curl

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
